# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('finishdate', models.DateField(blank=True, db_column='FinishDate', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('archive', models.BooleanField(db_column='Archive', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comissioner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('powertype', models.CharField(blank=True, db_column='PowerType', max_length=45, null=True)),
                ('certificatenumber', models.CharField(blank=True, db_column='CertificateNumber', max_length=45, null=True)),
                ('setdate', models.DateField(blank=True, db_column='SetDate', null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=45, null=True)),
                ('archive', models.BooleanField(db_column='Archive', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(blank=True, db_column='Number', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('archive', models.BooleanField(db_column='Archive', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Debter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.IntegerField(blank=True, db_column='Type', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('number', models.CharField(blank=True, db_column='Number', max_length=45, null=True)),
                ('kved', models.CharField(blank=True, db_column='KVED', max_length=45, null=True)),
                ('statepart', models.CharField(blank=True, db_column='StatePart', max_length=45, null=True)),
                ('actname', models.CharField(blank=True, db_column='ActName', max_length=45, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('archive', models.BooleanField(db_column='Archive', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('surname', models.CharField(blank=True, db_column='Surname', max_length=45, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=45, null=True)),
                ('archive', models.BooleanField(db_column='Archive', default=False)),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='comissionerid',
            field=models.ForeignKey(db_column='ComissionerId', on_delete=django.db.models.deletion.CASCADE, to='RestApi.Comissioner'),
        ),
        migrations.AddField(
            model_name='act',
            name='courtid',
            field=models.ForeignKey(db_column='CourtId', on_delete=django.db.models.deletion.CASCADE, to='RestApi.Court'),
        ),
        migrations.AddField(
            model_name='act',
            name='debterid',
            field=models.ForeignKey(db_column='DebterId', on_delete=django.db.models.deletion.CASCADE, to='RestApi.Debter'),
        ),
        migrations.AddField(
            model_name='act',
            name='judgeid',
            field=models.ForeignKey(db_column='JudgeId', on_delete=django.db.models.deletion.CASCADE, to='RestApi.Judge'),
        ),
    ]
